-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "investmentStep" DOUBLE PRECISION NOT NULL DEFAULT 100000,
ADD COLUMN     "maxInvestment" DOUBLE PRECISION,
ADD COLUMN     "minInvestment" DOUBLE PRECISION NOT NULL DEFAULT 100000,
ADD COLUMN     "projectionYears" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "roiCalculatorEnabled" BOOLEAN NOT NULL DEFAULT true;
